"""profile null

Revision ID: a79473ca136d
Revises: a935f1128843
Create Date: 2025-03-07 20:49:17.566176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79473ca136d'
down_revision: Union[str, None] = 'a935f1128843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('about_me', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'about_me')
    op.drop_column('profiles', 'photo_url')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
