"""profile data

Revision ID: a935f1128843
Revises: eb68574ad74a
Create Date: 2025-03-07 20:44:33.915051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a935f1128843'
down_revision: Union[str, None] = 'eb68574ad74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'about_me')
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'photo_url')
    op.drop_column('profiles', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('about_me', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
