# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'content_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontent_service.proto\x12\x0esocial_network\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n\x0bPostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncreator_id\x18\x03 \x01(\x05\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0f\n\x07private\x18\x05 \x01(\x08\"\xd1\x01\n\x0cPostResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreator_id\x18\x04 \x01(\x05\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04tags\x18\x07 \x03(\t\x12\x0f\n\x07private\x18\x08 \x01(\x08\" \n\rDeleteRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"c\n\rUpdateRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x0f\n\x07private\x18\x05 \x01(\x08\"0\n\nGetRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x11\n\tviewer_id\x18\x02 \x01(\x05\"=\n\x0bListRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x11\n\tviewer_id\x18\x03 \x01(\x05\"P\n\x0cListResponse\x12+\n\x05posts\x18\x01 \x03(\x0b\x32\x1c.social_network.PostResponse\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xfb\x02\n\x0bPostService\x12G\n\nCreatePost\x12\x1b.social_network.PostRequest\x1a\x1c.social_network.PostResponse\x12K\n\nDeletePost\x12\x1d.social_network.DeleteRequest\x1a\x1e.social_network.StatusResponse\x12I\n\nUpdatePost\x12\x1d.social_network.UpdateRequest\x1a\x1c.social_network.PostResponse\x12\x43\n\x07GetPost\x12\x1a.social_network.GetRequest\x1a\x1c.social_network.PostResponse\x12\x46\n\tListPosts\x12\x1b.social_network.ListRequest\x1a\x1c.social_network.ListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTREQUEST']._serialized_start=74
  _globals['_POSTREQUEST']._serialized_end=174
  _globals['_POSTRESPONSE']._serialized_start=177
  _globals['_POSTRESPONSE']._serialized_end=386
  _globals['_DELETEREQUEST']._serialized_start=388
  _globals['_DELETEREQUEST']._serialized_end=420
  _globals['_UPDATEREQUEST']._serialized_start=422
  _globals['_UPDATEREQUEST']._serialized_end=521
  _globals['_GETREQUEST']._serialized_start=523
  _globals['_GETREQUEST']._serialized_end=571
  _globals['_LISTREQUEST']._serialized_start=573
  _globals['_LISTREQUEST']._serialized_end=634
  _globals['_LISTRESPONSE']._serialized_start=636
  _globals['_LISTRESPONSE']._serialized_end=716
  _globals['_STATUSRESPONSE']._serialized_start=718
  _globals['_STATUSRESPONSE']._serialized_end=768
  _globals['_POSTSERVICE']._serialized_start=771
  _globals['_POSTSERVICE']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
