# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stats_service.proto\x12\x0esocial_network\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n\x0fGetStatsRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"3\n\x10GetStatsResponse\x12\r\n\x05likes\x18\x01 \x01(\x05\x12\x10\n\x08\x63omments\x18\x02 \x01(\x05\x32]\n\x0cStatsService\x12M\n\x08GetStats\x12\x1f.social_network.GetStatsRequest\x1a .social_network.GetStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATSREQUEST']._serialized_start=72
  _globals['_GETSTATSREQUEST']._serialized_end=106
  _globals['_GETSTATSRESPONSE']._serialized_start=108
  _globals['_GETSTATSRESPONSE']._serialized_end=159
  _globals['_STATSSERVICE']._serialized_start=161
  _globals['_STATSSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
