"""fix user_id

Revision ID: dee4d5b5a834
Revises: f4b50fd08799
Create Date: 2025-04-01 10:59:04.156333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee4d5b5a834'
down_revision: Union[str, None] = 'f4b50fd08799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_user_id_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_user_id_key', 'posts', ['user_id'])
    # ### end Alembic commands ###
